//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncfusion.Addin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syncfusion.Addin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtLeastOnePluginsPathMustBeSpecified!.
        /// </summary>
        internal static string AtLeastOnePluginsPathMustBeSpecified {
            get {
                return ResourceManager.GetString("AtLeastOnePluginsPathMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICE_ARGUMENT_NULL_EXCEPTION.
        /// </summary>
        internal static string BundleContext_RegisterService_SERVICE_ARGUMENT_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("BundleContext_RegisterService_SERVICE_ARGUMENT_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not instance of class.
        /// </summary>
        internal static string BundleContext_RegisterService_Service_is_not_instance_of_class {
            get {
                return ResourceManager.GetString("BundleContext_RegisterService_Service_is_not_instance_of_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File Overflow!!!.
        /// </summary>
        internal static string LogFileOverflow {
            get {
                return ResourceManager.GetString("LogFileOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton No Allowed!.
        /// </summary>
        internal static string SingletonNO {
            get {
                return ResourceManager.GetString("SingletonNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toplevelAssemb is null ,maybe is not web app,plase use PluginManage.WinAppLaunch() again!.
        /// </summary>
        internal static string TopAssemlyError {
            get {
                return ResourceManager.GetString("TopAssemlyError", resourceCulture);
            }
        }
    }
}
